### ISSUE TITLE
create_repository.py: version check is hardcoded to check for a fixed version string format

### ISSUE THREAD

**Issue by solbu** [chadparry/kodi-repository.chad.parry.org#4]
The script create_repository.py is hardcoded to check for exactly 3 version numbers.
In a repo I run localy I have an addon that are version formated as YYYY.MM.DD.REL, where REL is that days release. So if an addon have version 2017.07.20.1, your script says the version number is invalid.

If I change the string `'\d+\.\d+\.\d+$'` into `'\d+\.\d+\.\d+\.\d+$'`, it works, but only for addons having 4 numbers in the version string. E.G. 1.2.3 become an invalid version string, whereas 1.2.3.4 is now valid.

I've been using it since december 2016, and except for this bug it works nicely. :-)

**Comment by chadparry** [comment]
You'll probably want to continue using your fork of the script that allows 4-component version numbers. I've written below about the rationale for hard-coding the expectation of versions with 3 numbers. As long as your current system works for you, that's a fine solution for everybody.

The format with 3 version numbers is the one that is documented at http://kodi.wiki/view/addon.xml#version_attribute. That kind of format was created to support semantic versioning, which I highly recommend: http://semver.org/. The 4-number version string is not compatible with semantic versioning, and the Kodi documentation doesn't list any support for it. It may break with some Kodi versions. Even if it works, it is not officially supported, and could break in the future.

So for the safety of add-on authors, I think the script should continue to enforce the correct version string format. You may want to consider adopting the SemVer style version numbers for your own add-on, since then Kodi will be able to compare your version strings accurately, and it will always recognize which of your versions is the newest one.

That said, I noticed that the script doesn't use quite the correct regular expression for validating version strings. After the three version numbers, it should allow an optional "-label" or "+metadata" suffix. I'll expand the functionality to allow suffixes.

**Comment by solbu** [comment]
Aha. That make sense.

The addon in question is not mine, it's one I have in my own local repo. (It's Specto btw)
I've been replacing the version by changing the version to YYYY.MM.DD  and increasing the date by one. to make it work.

Reading your response I'll continue fixing the verison for new releases, to comply with the standard.
