### ISSUE TITLE
Addon archive creation MD5 change

### ISSUE THREAD

**Issue by SylvainCecchetto** [chadparry/kodi-repository.chad.parry.org#7]
Hi,

Thank you for your script!

But I have a question, do you know why the MD5 of my add-on zip change between two `create_repository.py` calls even if my add-on sources folder has not changed?

Thank you.

**Comment by chadparry** [comment]
I didn't know either at first. When the `create_repository.py` script runs, it clones your source files anew for each run. The file metadata, such as the creation time, ends up being different from run to run. That metadata is captured in the ZIP format. So the MD5 changes because the timestamps have changed.

If you wanted to have stable MD5 hash codes, that's possible too. Just keep an up-to-date local copy of your git repository, and supply its path instead of the live repository URL to `create_repository.py`.

**Comment by SylvainCecchetto** [comment]
Thank you for the details and for the tip!
